GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Another blog post",
    "author": "Tester",
    "url": "www.anothertest.com",
    "likes": "5"
}